FUNCTION_ANALYSIS_PROMPT = """
Analyze the given function signature and list each parameter with its data type and any initialization requirements.
Function signature:
```
{function_signature}
```
Your analysis should include the purpose of each parameter if known, and how it should be initialized for a valid test.
"""

FUZZING_HARNESS_GEN_PROMPT = """
Based on the function analysis below, generate a C++ fuzzing harness that initializes all parameters and calls the function.
- Use `FuzzedDataProvider` for input generation.
- Follow all provided guidelines strictly.
- Ensure all types match, and handle cases where initialization might fail gracefully.
Function analysis:
{function_analysis}

Guidelines:
{guidelines}

Function to fuzz:
```
{function_signature}
```
C++ fuzzing harness:
"""

COMPILE_PROMPT_TEMPLATE = """You are a c/c++ compiling expert.  
    The existing file name of fuzzing driver is `{harness_path}`.
    Do not use other C code or CPP code starting with `$SRC` from the build script.
    Please find the build command for compiling a single fuzzing driver for target project from the build script below.
    (Note: please replace $CC with clang and $CXX with clang++; remove environment variables at the CMD like `$CFLAGS` and `$CXXFLAGS` ;
    show the code as output only): 
    ```
        {code}
    ```
    Show me the compile command only, no other text.
    """

LINK_PROMPT_TEMPLATE = """You are a c/c++ compiling expert.  
    The existing file name of fuzzing driver is `{harness_path}`.
    Please find the build command for linking a single fuzzing driver with Libfuzzer for target project from the build script below so that we can start running the fuzzer.

    (Note: please replace $CC with clang and $CXX with clang++; remove environment variables at the CMD like `$CFLAGS` and `$CXXFLAGS`;
     the name of output binary is `./fuzz_harness` ; add essential linking flags for Libfuzzer; show the code as output only): 
    ```
        {code}
    ```

    The compile-only command is showed as below
    ```
        {compile_line}
    ```

    Show me the command for linkage only, no other text.
    """


# CODE_FIX_PROMPT = """
# Given the following code for the harness file from oss-fuzz project {project_name} and its build error message, fix the code without affecting its functionality. 
# First explain the reason, then output the whole fixed code. 
 
# 1. If a function is missing, fix it by including the related libraries. 
# 2. If the compiler cannot find the head file, you should first check it in the provided header information. 

# Code:
# {harness_code}

# Build error message:
# {error_msg}

# Header Information:
# {header_files}

# Fixed code:
# """


# CODE_FIX_PROMPT_TOOLS = """
# Given the following code for the harness file from oss-fuzz project {project_name} and its build error message, fix the code without affecting its functionality. 
# First explain the reason, then output the whole fixed code. 

# 1. If a function is missing, fix it by including the related libraries. 
# 2. If the compile cannot find the head file, you can call the tool to find the correct location of the head file. 
# 3. The correct location of the head file from the tool is provided in the header information.

# Code:
# ```
# {harness_code}
# ```
# Build error messages:
# ```
# {error_msg}
# ```
# Header Information From Tool:
# {header_files}

# Fixed code:
# """

CODE_FIX_PROMPT = '''
```
{harness_code}
```

The above {project_lang} code has compilation error.


The error description is: 
{error_msg}

Based on the above information, fix the code. Must provide the full fixed code.
'''

EXTRACT_CODE_PROMPT = """
The following code is generated by the LLM. It may contains unnecessary explanation before and after the code. Please split the response into three parts: before code, code, and after code.

{response}
"""


FUZZ_FIX_PROMPT = '''
```
{harness_code}
```

The above {project_lang} code can be built successfully but has the following errors when runing fuzzer.

{error_msg}

Based on the above information, fix the code. Must provide the full fixed code.

'''

INIT_PROMPT = '''

// Write a fuzz driver in {project_lang} language for the given function. Output the full harness code.
// Using absolute path when including project header file.
// Do not fake the struct or class definition, use the one provided by the tool.
// @ examples of API usage
{function_usage}

{function_document}

// Fuzz function signature
{function_name}

'''